-- Weekly Schedule — 20 Jul to 9 Aug 2026, generated by AviCore's planner
-- from the published duty roster ("NEW Pilot Schedule 2026 (Include RR9)",
-- sheet "RR 2026") with every rule agreed in docs/WEEKLY-SCHEDULE-RULES.md:
--
--   * only pilots the roster shows on duty (O / N / ND)
--   * 12h minimum rest between duty end and next report
--     (night ends 05:30 -> earliest next report 17:30)
--   * rolling duty limits respected, and planned to the WARNING figure,
--     not the legal maximum - a seat that could only be filled by pushing
--     someone into the yellow was left unmanned instead
--   * no more than 6 night duties per 28-day cycle
--   * rotation Night -> OFF -> Crew 1 -> Crew 3 -> Crew 2 -> Crew 4
--   * pairing: never two Co-pilots; second seat prefers a Co-pilot
--   * work handed to whoever is carrying the least duty, and whoever has
--     flown least this cycle
--
-- RESULT: 165 assignments, zero red, zero yellow, zero conflicts.
-- Highest 7-day duty 53.5h (warning 54h, limit 60h); nights spread across
-- 18 pilots, nobody above 5.
--
-- Run AFTER sql/weekly-plan-setup.sql.
--
-- WHAT THIS RUN COULD NOT SEE: it was generated outside the app, so it has
-- no access to Night Currency, overdue training, recorded flight hours or
-- the 168h Recovery Rest cycle. It assumes every pilot is night current and
-- fully in date. Once loaded, press "Plan 30 Days" in the app to regenerate
-- against the real records - that result supersedes this one.

begin;

update public.pilot_weekly_plan
   set deleted_at = now()::text, modified_at = now()::text
 where date between '2026-07-20' and '2026-08-09'
   and deleted_at is null;

insert into public.pilot_weekly_plan
  (uuid, device_id, date, section, slot, pilot_code, level, created_at, modified_at, deleted_at)
values
  ('2026-07-20_crew1_0', 'planner-2026-07-20', '2026-07-20', 'crew1', 0, 'KPO', 4, now()::text, now()::text, null),
  ('2026-07-20_crew1_1', 'planner-2026-07-20', '2026-07-20', 'crew1', 1, 'KTO', 3, now()::text, now()::text, null),
  ('2026-07-20_crew2_0', 'planner-2026-07-20', '2026-07-20', 'crew2', 0, 'NKR', 3, now()::text, now()::text, null),
  ('2026-07-20_crew2_1', 'planner-2026-07-20', '2026-07-20', 'crew2', 1, 'NSO', 4, now()::text, now()::text, null),
  ('2026-07-20_crew3_0', 'planner-2026-07-20', '2026-07-20', 'crew3', 0, 'PCH', 3, now()::text, now()::text, null),
  ('2026-07-20_crew3_1', 'planner-2026-07-20', '2026-07-20', 'crew3', 1, 'PKR', 3, now()::text, now()::text, null),
  ('2026-07-20_crew4_0', 'planner-2026-07-20', '2026-07-20', 'crew4', 0, 'TBO', 4, now()::text, now()::text, null),
  ('2026-07-20_crew4_1', 'planner-2026-07-20', '2026-07-20', 'crew4', 1, 'YLU', 3, now()::text, now()::text, null),
  ('2026-07-20_nightStandby1_0', 'planner-2026-07-20', '2026-07-20', 'nightStandby1', 0, 'CSU', 3, now()::text, now()::text, null),
  ('2026-07-20_nightStandby1_1', 'planner-2026-07-20', '2026-07-20', 'nightStandby1', 1, 'KCH', 3, now()::text, now()::text, null),
  ('2026-07-21_crew1_0', 'planner-2026-07-20', '2026-07-21', 'crew1', 0, 'YLU', 3, now()::text, now()::text, null),
  ('2026-07-21_crew1_1', 'planner-2026-07-20', '2026-07-21', 'crew1', 1, 'WTH', 3, now()::text, now()::text, null),
  ('2026-07-21_crew2_0', 'planner-2026-07-20', '2026-07-21', 'crew2', 0, 'PCH', 3, now()::text, now()::text, null),
  ('2026-07-21_crew2_1', 'planner-2026-07-20', '2026-07-21', 'crew2', 1, 'PKR', 3, now()::text, now()::text, null),
  ('2026-07-21_crew3_0', 'planner-2026-07-20', '2026-07-21', 'crew3', 0, 'NKR', 3, now()::text, now()::text, null),
  ('2026-07-21_crew3_1', 'planner-2026-07-20', '2026-07-21', 'crew3', 1, 'KTO', 3, now()::text, now()::text, null),
  ('2026-07-21_nightStandby1_0', 'planner-2026-07-20', '2026-07-21', 'nightStandby1', 0, 'TBO', 4, now()::text, now()::text, null),
  ('2026-07-21_nightStandby1_1', 'planner-2026-07-20', '2026-07-21', 'nightStandby1', 1, 'RPA', 3, now()::text, now()::text, null),
  ('2026-07-22_crew1_0', 'planner-2026-07-20', '2026-07-22', 'crew1', 0, 'CSU', 3, now()::text, now()::text, null),
  ('2026-07-22_crew1_1', 'planner-2026-07-20', '2026-07-22', 'crew1', 1, 'KCH', 3, now()::text, now()::text, null),
  ('2026-07-22_crew2_0', 'planner-2026-07-20', '2026-07-22', 'crew2', 0, 'NKR', 3, now()::text, now()::text, null),
  ('2026-07-22_crew2_1', 'planner-2026-07-20', '2026-07-22', 'crew2', 1, 'WTH', 3, now()::text, now()::text, null),
  ('2026-07-22_crew3_0', 'planner-2026-07-20', '2026-07-22', 'crew3', 0, 'PCH', 3, now()::text, now()::text, null),
  ('2026-07-22_crew3_1', 'planner-2026-07-20', '2026-07-22', 'crew3', 1, 'PKR', 3, now()::text, now()::text, null),
  ('2026-07-22_nightStandby1_0', 'planner-2026-07-20', '2026-07-22', 'nightStandby1', 0, 'WJU', 4, now()::text, now()::text, null),
  ('2026-07-22_nightStandby1_1', 'planner-2026-07-20', '2026-07-22', 'nightStandby1', 1, 'TYO', 3, now()::text, now()::text, null),
  ('2026-07-23_crew1_0', 'planner-2026-07-20', '2026-07-23', 'crew1', 0, 'PCH', 3, now()::text, now()::text, null),
  ('2026-07-23_crew1_1', 'planner-2026-07-20', '2026-07-23', 'crew1', 1, 'RPA', 3, now()::text, now()::text, null),
  ('2026-07-23_crew2_0', 'planner-2026-07-20', '2026-07-23', 'crew2', 0, 'KPO', 4, now()::text, now()::text, null),
  ('2026-07-23_crew2_1', 'planner-2026-07-20', '2026-07-23', 'crew2', 1, 'PKR', 3, now()::text, now()::text, null),
  ('2026-07-23_crew3_0', 'planner-2026-07-20', '2026-07-23', 'crew3', 0, 'CSU', 3, now()::text, now()::text, null),
  ('2026-07-23_crew3_1', 'planner-2026-07-20', '2026-07-23', 'crew3', 1, 'KCH', 3, now()::text, now()::text, null),
  ('2026-07-23_nightStandby1_0', 'planner-2026-07-20', '2026-07-23', 'nightStandby1', 0, 'NKR', 3, now()::text, now()::text, null),
  ('2026-07-23_nightStandby1_1', 'planner-2026-07-20', '2026-07-23', 'nightStandby1', 1, 'WTH', 3, now()::text, now()::text, null),
  ('2026-07-24_crew1_0', 'planner-2026-07-20', '2026-07-24', 'crew1', 0, 'WJU', 4, now()::text, now()::text, null),
  ('2026-07-24_crew1_1', 'planner-2026-07-20', '2026-07-24', 'crew1', 1, 'TYO', 3, now()::text, now()::text, null),
  ('2026-07-24_crew2_0', 'planner-2026-07-20', '2026-07-24', 'crew2', 0, 'CSU', 3, now()::text, now()::text, null),
  ('2026-07-24_crew2_1', 'planner-2026-07-20', '2026-07-24', 'crew2', 1, 'KTO', 3, now()::text, now()::text, null),
  ('2026-07-24_crew3_0', 'planner-2026-07-20', '2026-07-24', 'crew3', 0, 'PCH', 3, now()::text, now()::text, null),
  ('2026-07-24_crew3_1', 'planner-2026-07-20', '2026-07-24', 'crew3', 1, 'RPA', 3, now()::text, now()::text, null),
  ('2026-07-24_crew4_0', 'planner-2026-07-20', '2026-07-24', 'crew4', 0, 'TBO', 4, now()::text, now()::text, null),
  ('2026-07-24_crew4_1', 'planner-2026-07-20', '2026-07-24', 'crew4', 1, 'KCH', 3, now()::text, now()::text, null),
  ('2026-07-24_nightStandby1_0', 'planner-2026-07-20', '2026-07-24', 'nightStandby1', 0, 'KPO', 4, now()::text, now()::text, null),
  ('2026-07-24_nightStandby1_1', 'planner-2026-07-20', '2026-07-24', 'nightStandby1', 1, 'PKR', 3, now()::text, now()::text, null),
  ('2026-07-25_crew1_0', 'planner-2026-07-20', '2026-07-25', 'crew1', 0, 'TBO', 4, now()::text, now()::text, null),
  ('2026-07-25_crew1_1', 'planner-2026-07-20', '2026-07-25', 'crew1', 1, 'WTH', 3, now()::text, now()::text, null),
  ('2026-07-25_crew2_0', 'planner-2026-07-20', '2026-07-25', 'crew2', 0, 'WJU', 4, now()::text, now()::text, null),
  ('2026-07-25_crew2_1', 'planner-2026-07-20', '2026-07-25', 'crew2', 1, 'RPA', 3, now()::text, now()::text, null),
  ('2026-07-25_nightStandby1_0', 'planner-2026-07-20', '2026-07-25', 'nightStandby1', 0, 'PDE', 4, now()::text, now()::text, null),
  ('2026-07-25_nightStandby1_1', 'planner-2026-07-20', '2026-07-25', 'nightStandby1', 1, 'PME', 3, now()::text, now()::text, null),
  ('2026-07-26_crew1_0', 'planner-2026-07-20', '2026-07-26', 'crew1', 0, 'KPO', 4, now()::text, now()::text, null),
  ('2026-07-26_crew1_1', 'planner-2026-07-20', '2026-07-26', 'crew1', 1, 'KTO', 3, now()::text, now()::text, null),
  ('2026-07-26_nightStandby1_0', 'planner-2026-07-20', '2026-07-26', 'nightStandby1', 0, 'TBO', 4, now()::text, now()::text, null),
  ('2026-07-26_nightStandby1_1', 'planner-2026-07-20', '2026-07-26', 'nightStandby1', 1, 'KCH', 3, now()::text, now()::text, null),
  ('2026-07-27_crew1_0', 'planner-2026-07-20', '2026-07-27', 'crew1', 0, 'PDE', 4, now()::text, now()::text, null),
  ('2026-07-27_crew1_1', 'planner-2026-07-20', '2026-07-27', 'crew1', 1, 'PME', 3, now()::text, now()::text, null),
  ('2026-07-27_crew2_0', 'planner-2026-07-20', '2026-07-27', 'crew2', 0, 'KPO', 4, now()::text, now()::text, null),
  ('2026-07-27_crew2_1', 'planner-2026-07-20', '2026-07-27', 'crew2', 1, 'TYO', 3, now()::text, now()::text, null),
  ('2026-07-27_crew3_0', 'planner-2026-07-20', '2026-07-27', 'crew3', 0, 'CSU', 3, now()::text, now()::text, null),
  ('2026-07-27_crew3_1', 'planner-2026-07-20', '2026-07-27', 'crew3', 1, 'WTH', 3, now()::text, now()::text, null),
  ('2026-07-27_nightStandby1_0', 'planner-2026-07-20', '2026-07-27', 'nightStandby1', 0, 'WJU', 4, now()::text, now()::text, null),
  ('2026-07-27_nightStandby1_1', 'planner-2026-07-20', '2026-07-27', 'nightStandby1', 1, 'KTO', 3, now()::text, now()::text, null),
  ('2026-07-28_crew1_0', 'planner-2026-07-20', '2026-07-28', 'crew1', 0, 'TBO', 4, now()::text, now()::text, null),
  ('2026-07-28_crew1_1', 'planner-2026-07-20', '2026-07-28', 'crew1', 1, 'KCH', 3, now()::text, now()::text, null),
  ('2026-07-28_crew2_0', 'planner-2026-07-20', '2026-07-28', 'crew2', 0, 'CSU', 3, now()::text, now()::text, null),
  ('2026-07-28_crew2_1', 'planner-2026-07-20', '2026-07-28', 'crew2', 1, 'TYO', 3, now()::text, now()::text, null),
  ('2026-07-28_crew3_0', 'planner-2026-07-20', '2026-07-28', 'crew3', 0, 'KPO', 4, now()::text, now()::text, null),
  ('2026-07-28_crew3_1', 'planner-2026-07-20', '2026-07-28', 'crew3', 1, 'RPA', 3, now()::text, now()::text, null),
  ('2026-07-28_nightStandby1_0', 'planner-2026-07-20', '2026-07-28', 'nightStandby1', 0, 'PIN', 3, now()::text, now()::text, null),
  ('2026-07-28_nightStandby1_1', 'planner-2026-07-20', '2026-07-28', 'nightStandby1', 1, 'KSU', 4, now()::text, now()::text, null),
  ('2026-07-29_crew1_0', 'planner-2026-07-20', '2026-07-29', 'crew1', 0, 'WJU', 4, now()::text, now()::text, null),
  ('2026-07-29_crew1_1', 'planner-2026-07-20', '2026-07-29', 'crew1', 1, 'KTO', 3, now()::text, now()::text, null),
  ('2026-07-29_crew2_0', 'planner-2026-07-20', '2026-07-29', 'crew2', 0, 'PDE', 4, now()::text, now()::text, null),
  ('2026-07-29_crew2_1', 'planner-2026-07-20', '2026-07-29', 'crew2', 1, 'RPA', 3, now()::text, now()::text, null),
  ('2026-07-29_nightStandby1_0', 'planner-2026-07-20', '2026-07-29', 'nightStandby1', 0, 'CSU', 3, now()::text, now()::text, null),
  ('2026-07-29_nightStandby1_1', 'planner-2026-07-20', '2026-07-29', 'nightStandby1', 1, 'TYO', 3, now()::text, now()::text, null),
  ('2026-07-30_crew1_0', 'planner-2026-07-20', '2026-07-30', 'crew1', 0, 'PIN', 3, now()::text, now()::text, null),
  ('2026-07-30_crew1_1', 'planner-2026-07-20', '2026-07-30', 'crew1', 1, 'KSU', 4, now()::text, now()::text, null),
  ('2026-07-30_crew2_0', 'planner-2026-07-20', '2026-07-30', 'crew2', 0, 'WJU', 4, now()::text, now()::text, null),
  ('2026-07-30_crew2_1', 'planner-2026-07-20', '2026-07-30', 'crew2', 1, 'PME', 3, now()::text, now()::text, null),
  ('2026-07-30_nightStandby1_0', 'planner-2026-07-20', '2026-07-30', 'nightStandby1', 0, 'PDE', 4, now()::text, now()::text, null),
  ('2026-07-30_nightStandby1_1', 'planner-2026-07-20', '2026-07-30', 'nightStandby1', 1, 'RPA', 3, now()::text, now()::text, null),
  ('2026-07-31_crew1_0', 'planner-2026-07-20', '2026-07-31', 'crew1', 0, 'CSU', 3, now()::text, now()::text, null),
  ('2026-07-31_crew1_1', 'planner-2026-07-20', '2026-07-31', 'crew1', 1, 'TYO', 3, now()::text, now()::text, null),
  ('2026-07-31_crew2_0', 'planner-2026-07-20', '2026-07-31', 'crew2', 0, 'YLU', 3, now()::text, now()::text, null),
  ('2026-07-31_crew2_1', 'planner-2026-07-20', '2026-07-31', 'crew2', 1, 'KSU', 4, now()::text, now()::text, null),
  ('2026-07-31_crew3_0', 'planner-2026-07-20', '2026-07-31', 'crew3', 0, 'TBO', 4, now()::text, now()::text, null),
  ('2026-07-31_crew3_1', 'planner-2026-07-20', '2026-07-31', 'crew3', 1, 'KCH', 3, now()::text, now()::text, null),
  ('2026-07-31_nightStandby1_0', 'planner-2026-07-20', '2026-07-31', 'nightStandby1', 0, 'WJU', 4, now()::text, now()::text, null),
  ('2026-07-31_nightStandby1_1', 'planner-2026-07-20', '2026-07-31', 'nightStandby1', 1, 'NSO', 4, now()::text, now()::text, null),
  ('2026-08-01_crew1_0', 'planner-2026-07-20', '2026-08-01', 'crew1', 0, 'PDE', 4, now()::text, now()::text, null),
  ('2026-08-01_crew1_1', 'planner-2026-07-20', '2026-08-01', 'crew1', 1, 'RPA', 3, now()::text, now()::text, null),
  ('2026-08-01_crew2_0', 'planner-2026-07-20', '2026-08-01', 'crew2', 0, 'TBO', 4, now()::text, now()::text, null),
  ('2026-08-01_crew2_1', 'planner-2026-07-20', '2026-08-01', 'crew2', 1, 'KCH', 3, now()::text, now()::text, null),
  ('2026-08-01_crew3_0', 'planner-2026-07-20', '2026-08-01', 'crew3', 0, 'PIN', 3, now()::text, now()::text, null),
  ('2026-08-01_crew3_1', 'planner-2026-07-20', '2026-08-01', 'crew3', 1, 'TYO', 3, now()::text, now()::text, null),
  ('2026-08-01_crew4_0', 'planner-2026-07-20', '2026-08-01', 'crew4', 0, 'CSU', 3, now()::text, now()::text, null),
  ('2026-08-01_nightStandby1_0', 'planner-2026-07-20', '2026-08-01', 'nightStandby1', 0, 'YLU', 3, now()::text, now()::text, null),
  ('2026-08-01_nightStandby1_1', 'planner-2026-07-20', '2026-08-01', 'nightStandby1', 1, 'PME', 3, now()::text, now()::text, null),
  ('2026-08-02_crew1_0', 'planner-2026-07-20', '2026-08-02', 'crew1', 0, 'NKR', 3, now()::text, now()::text, null),
  ('2026-08-02_crew1_1', 'planner-2026-07-20', '2026-08-02', 'crew1', 1, 'NSO', 4, now()::text, now()::text, null),
  ('2026-08-02_crew2_0', 'planner-2026-07-20', '2026-08-02', 'crew2', 0, 'PIN', 3, now()::text, now()::text, null),
  ('2026-08-02_crew2_1', 'planner-2026-07-20', '2026-08-02', 'crew2', 1, 'RPA', 3, now()::text, now()::text, null),
  ('2026-08-02_crew3_0', 'planner-2026-07-20', '2026-08-02', 'crew3', 0, 'PDE', 4, now()::text, now()::text, null),
  ('2026-08-02_crew3_1', 'planner-2026-07-20', '2026-08-02', 'crew3', 1, 'KCH', 3, now()::text, now()::text, null),
  ('2026-08-02_nightStandby1_0', 'planner-2026-07-20', '2026-08-02', 'nightStandby1', 0, 'TBO', 4, now()::text, now()::text, null),
  ('2026-08-02_nightStandby1_1', 'planner-2026-07-20', '2026-08-02', 'nightStandby1', 1, 'KSU', 4, now()::text, now()::text, null),
  ('2026-08-03_crew1_0', 'planner-2026-07-20', '2026-08-03', 'crew1', 0, 'YLU', 3, now()::text, now()::text, null),
  ('2026-08-03_crew1_1', 'planner-2026-07-20', '2026-08-03', 'crew1', 1, 'PME', 3, now()::text, now()::text, null),
  ('2026-08-03_crew2_0', 'planner-2026-07-20', '2026-08-03', 'crew2', 0, 'PDE', 4, now()::text, now()::text, null),
  ('2026-08-03_crew2_1', 'planner-2026-07-20', '2026-08-03', 'crew2', 1, 'NSO', 4, now()::text, now()::text, null),
  ('2026-08-03_crew3_0', 'planner-2026-07-20', '2026-08-03', 'crew3', 0, 'NKR', 3, now()::text, now()::text, null),
  ('2026-08-03_crew3_1', 'planner-2026-07-20', '2026-08-03', 'crew3', 1, 'PKR', 3, now()::text, now()::text, null),
  ('2026-08-03_crew4_0', 'planner-2026-07-20', '2026-08-03', 'crew4', 0, 'WJU', 4, now()::text, now()::text, null),
  ('2026-08-03_nightStandby1_0', 'planner-2026-07-20', '2026-08-03', 'nightStandby1', 0, 'PIN', 3, now()::text, now()::text, null),
  ('2026-08-03_nightStandby1_1', 'planner-2026-07-20', '2026-08-03', 'nightStandby1', 1, 'KCH', 3, now()::text, now()::text, null),
  ('2026-08-04_crew1_0', 'planner-2026-07-20', '2026-08-04', 'crew1', 0, 'TBO', 4, now()::text, now()::text, null),
  ('2026-08-04_crew1_1', 'planner-2026-07-20', '2026-08-04', 'crew1', 1, 'KSU', 4, now()::text, now()::text, null),
  ('2026-08-04_crew2_0', 'planner-2026-07-20', '2026-08-04', 'crew2', 0, 'NKR', 3, now()::text, now()::text, null),
  ('2026-08-04_crew2_1', 'planner-2026-07-20', '2026-08-04', 'crew2', 1, 'PKR', 3, now()::text, now()::text, null),
  ('2026-08-04_nightStandby1_0', 'planner-2026-07-20', '2026-08-04', 'nightStandby1', 0, 'WJU', 4, now()::text, now()::text, null),
  ('2026-08-04_nightStandby1_1', 'planner-2026-07-20', '2026-08-04', 'nightStandby1', 1, 'NSO', 4, now()::text, now()::text, null),
  ('2026-08-05_crew1_0', 'planner-2026-07-20', '2026-08-05', 'crew1', 0, 'PIN', 3, now()::text, now()::text, null),
  ('2026-08-05_crew1_1', 'planner-2026-07-20', '2026-08-05', 'crew1', 1, 'KCH', 3, now()::text, now()::text, null),
  ('2026-08-05_crew2_0', 'planner-2026-07-20', '2026-08-05', 'crew2', 0, 'PCH', 3, now()::text, now()::text, null),
  ('2026-08-05_crew2_1', 'planner-2026-07-20', '2026-08-05', 'crew2', 1, 'TYO', 3, now()::text, now()::text, null),
  ('2026-08-05_crew3_0', 'planner-2026-07-20', '2026-08-05', 'crew3', 0, 'YLU', 3, now()::text, now()::text, null),
  ('2026-08-05_crew3_1', 'planner-2026-07-20', '2026-08-05', 'crew3', 1, 'KSU', 4, now()::text, now()::text, null),
  ('2026-08-05_crew4_0', 'planner-2026-07-20', '2026-08-05', 'crew4', 0, 'TBO', 4, now()::text, now()::text, null),
  ('2026-08-05_nightStandby1_0', 'planner-2026-07-20', '2026-08-05', 'nightStandby1', 0, 'NKR', 3, now()::text, now()::text, null),
  ('2026-08-05_nightStandby1_1', 'planner-2026-07-20', '2026-08-05', 'nightStandby1', 1, 'PKR', 3, now()::text, now()::text, null),
  ('2026-08-06_crew1_0', 'planner-2026-07-20', '2026-08-06', 'crew1', 0, 'WJU', 4, now()::text, now()::text, null),
  ('2026-08-06_crew1_1', 'planner-2026-07-20', '2026-08-06', 'crew1', 1, 'NSO', 4, now()::text, now()::text, null),
  ('2026-08-06_crew2_0', 'planner-2026-07-20', '2026-08-06', 'crew2', 0, 'YLU', 3, now()::text, now()::text, null),
  ('2026-08-06_crew2_1', 'planner-2026-07-20', '2026-08-06', 'crew2', 1, 'WTH', 3, now()::text, now()::text, null),
  ('2026-08-06_crew3_0', 'planner-2026-07-20', '2026-08-06', 'crew3', 0, 'PIN', 3, now()::text, now()::text, null),
  ('2026-08-06_crew3_1', 'planner-2026-07-20', '2026-08-06', 'crew3', 1, 'PME', 3, now()::text, now()::text, null),
  ('2026-08-06_crew4_0', 'planner-2026-07-20', '2026-08-06', 'crew4', 0, 'PCH', 3, now()::text, now()::text, null),
  ('2026-08-06_crew4_1', 'planner-2026-07-20', '2026-08-06', 'crew4', 1, 'KSU', 4, now()::text, now()::text, null),
  ('2026-08-06_crew5_0', 'planner-2026-07-20', '2026-08-06', 'crew5', 0, 'PDE', 4, now()::text, now()::text, null),
  ('2026-08-06_crew5_1', 'planner-2026-07-20', '2026-08-06', 'crew5', 1, 'KCH', 3, now()::text, now()::text, null),
  ('2026-08-06_nightStandby1_0', 'planner-2026-07-20', '2026-08-06', 'nightStandby1', 0, 'TBO', 4, now()::text, now()::text, null),
  ('2026-08-06_nightStandby1_1', 'planner-2026-07-20', '2026-08-06', 'nightStandby1', 1, 'TYO', 3, now()::text, now()::text, null),
  ('2026-08-07_crew1_0', 'planner-2026-07-20', '2026-08-07', 'crew1', 0, 'PDE', 4, now()::text, now()::text, null),
  ('2026-08-07_crew1_1', 'planner-2026-07-20', '2026-08-07', 'crew1', 1, 'PME', 3, now()::text, now()::text, null),
  ('2026-08-07_crew2_0', 'planner-2026-07-20', '2026-08-07', 'crew2', 0, 'WJU', 4, now()::text, now()::text, null),
  ('2026-08-07_crew2_1', 'planner-2026-07-20', '2026-08-07', 'crew2', 1, 'NSO', 4, now()::text, now()::text, null),
  ('2026-08-07_crew3_0', 'planner-2026-07-20', '2026-08-07', 'crew3', 0, 'NKR', 3, now()::text, now()::text, null),
  ('2026-08-07_crew3_1', 'planner-2026-07-20', '2026-08-07', 'crew3', 1, 'YLU', 3, now()::text, now()::text, null),
  ('2026-08-07_nightStandby1_0', 'planner-2026-07-20', '2026-08-07', 'nightStandby1', 0, 'PCH', 3, now()::text, now()::text, null),
  ('2026-08-07_nightStandby1_1', 'planner-2026-07-20', '2026-08-07', 'nightStandby1', 1, 'WTH', 3, now()::text, now()::text, null),
  ('2026-08-08_crew1_0', 'planner-2026-07-20', '2026-08-08', 'crew1', 0, 'KPO', 4, now()::text, now()::text, null),
  ('2026-08-08_crew1_1', 'planner-2026-07-20', '2026-08-08', 'crew1', 1, 'TYO', 3, now()::text, now()::text, null),
  ('2026-08-08_crew2_0', 'planner-2026-07-20', '2026-08-08', 'crew2', 0, 'YLU', 3, now()::text, now()::text, null),
  ('2026-08-08_crew2_1', 'planner-2026-07-20', '2026-08-08', 'crew2', 1, 'PME', 3, now()::text, now()::text, null),
  ('2026-08-08_crew3_0', 'planner-2026-07-20', '2026-08-08', 'crew3', 0, 'PDE', 4, now()::text, now()::text, null),
  ('2026-08-08_crew3_1', 'planner-2026-07-20', '2026-08-08', 'crew3', 1, 'PKR', 3, now()::text, now()::text, null),
  ('2026-08-08_nightStandby1_0', 'planner-2026-07-20', '2026-08-08', 'nightStandby1', 0, 'WJU', 4, now()::text, now()::text, null),
  ('2026-08-08_nightStandby1_1', 'planner-2026-07-20', '2026-08-08', 'nightStandby1', 1, 'NSO', 4, now()::text, now()::text, null),
  ('2026-08-09_crew1_0', 'planner-2026-07-20', '2026-08-09', 'crew1', 0, 'PDE', 4, now()::text, now()::text, null),
  ('2026-08-09_crew1_1', 'planner-2026-07-20', '2026-08-09', 'crew1', 1, 'WTH', 3, now()::text, now()::text, null),
  ('2026-08-09_crew2_0', 'planner-2026-07-20', '2026-08-09', 'crew2', 0, 'KPO', 4, now()::text, now()::text, null),
  ('2026-08-09_crew2_1', 'planner-2026-07-20', '2026-08-09', 'crew2', 1, 'PKR', 3, now()::text, now()::text, null),
  ('2026-08-09_nightStandby1_0', 'planner-2026-07-20', '2026-08-09', 'nightStandby1', 0, 'NKR', 3, now()::text, now()::text, null),
  ('2026-08-09_nightStandby1_1', 'planner-2026-07-20', '2026-08-09', 'nightStandby1', 1, 'KSU', 4, now()::text, now()::text, null)

on conflict (uuid) do update set
  pilot_code  = excluded.pilot_code,
  level       = excluded.level,
  modified_at = excluded.modified_at,
  deleted_at  = null;

commit;

-- Check: should return 165
-- select count(*) from public.pilot_weekly_plan
--  where date between '2026-07-20' and '2026-08-09' and deleted_at is null;
